on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Tests
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run Tests
        if: ${{ runner.os == 'Windows' }}
        run: |
          ./build/typelist.exe
      - name: Run Tests
        if: ${{ runner.os == 'Linux' }}
        run: |
          ./build/typelist
      - name: Print
        run: |
          echo "runner.os is: ${{ runner.os }}"
