on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Tests
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run Tests
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd build

          ls -la

          ./typelist.exe > log.txt
      - name: Run Tests
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          ./build/typelist > log.txt

      - name: Match
        uses: ./lib/match/.github/public/build_and_validate
        with:
          working_directory: lib/match
          log_file: log.txt
          regex_file: test.regex
